Update readme
rlennon/smallwindow21 pull request #1
Opened 2021-06-11 13:12 UTC by L00163105

Update README teams Social Contract section

2021-06-11 17:46 UTC, JoseSunoj requested changes
line 128, Autoatedbot (Automated bot), line 150 TDB(TBD), line 183 spring(sprint). We can add internal links to the table of contents to avoid scrolling. 'For More Information' can be a sub-heading with contents as a table. One item in the table of contents named 'Considerations' is not having space in the file; either we can exclude it from the contents or add a section inside the file or ask Ruth about it. We can add bullets to the lists in 'Useful links'. May need a tab right to nicely align the team members.

2021-06-11 18:07 UTC, Robert-Tokarz approved these changes
Thanks for adding me to Rockstar.

2021-06-11 18:32 UTC, damogallagher approved these changes

2021-06-11 18:50 UTC, sharonO13 commented on README.md
> +    Stand-ups will occur on Every Wednesday during class and Fridays at 8pm GMT+1 using Autoatedbot.
Correction needed for Automated bot

2021-06-11 18:52 UTC, sharonO13 reviewed
Updates look good, just a spell check on the automated standup for Automated Bot

2021-06-12 16:15 UTC, JoseSunoj requested changes
Since we decided to move Friday's stand-up to Monday, we have to note the changes.

2021-06-13 15:09 UTC, L00163105 commented
> Since we decided to move Friday's stand-up to Monday, we have to note the changes.

Changed Friday references to Monday

2021-06-13 15:31 UTC, JoseSunoj requested changes
Please consider the following:
1. We can add internal links to the table of contents to avoid scrolling. 
2. 'For More Information' can be a sub-heading with contents as a table. 3. 
3. One item in the table of contents named 'Considerations' is not having space in the file (missing in the original file); either we can exclude it from the contents or add a section inside the file or ask Ruth about it. We can add bullets to the lists in 'Useful links'. 
4. May need a tab right to nicely align the team members.

2021-06-13 16:01 UTC, L00163105 commented
> Please consider the following:
> 
> 1. We can add internal links to the table of contents to avoid scrolling. / done
> 2. 'For More Information' can be a sub-heading with contents as a table. / done
> 3. One item in the table of contents named 'Considerations' is not having space in the file (missing in the original file); either we can exclude it from the contents or add a section inside the file or ask Ruth about it.  / not sure about this
> 4. We can add bullets to the lists in 'Useful links'. /done 
> 5. May need a tab right to nicely align the team members. /done

2021-06-13 16:54 UTC, JoseSunoj approved these changes

2021-06-13 16:54 UTC, merged