Readme updated dod dor
rlennon/smallwindow21 pull request #16
Opened 2021-06-28 19:42 UTC by sharonO13

Updated readme with Definition of Done and Definition of Ready as discussed in planning meeting

2021-06-28 23:03 UTC, JoseSunoj requested changes
I have a few suggestions:
1. if it follows under the section Other, then it will be nice. If you agree, then please change the headings as ### Definition of Ready,  #### Code, #### Documentation, ###Definition of Ready
2. please consider adding links to the Contents. 

Thanks.

2021-06-29 19:23 UTC, L00163105 approved these changes

2021-06-29 19:45 UTC, 97047619 approved these changes
Approved

2021-06-29 20:13 UTC, damogallagher approved these changes

2021-07-09 11:40 UTC, merged